import express from 'express'
import { authMiddleware } from '../middleware/authMiddleware.js'
import pool from '../config/pool.js'
import jwt from 'jsonwebtoken'

const securityRouter=express.Router()

securityRouter.post('/decodeGatepass',authMiddleware,async(req,res)=>{
    try {
        const gatepassToken=req.body.gatepassToken
        const secret=process.env.JWT_SECRET
        const decodedToken=await jwt.verify(gatepassToken,secret)
        return res.json({success:true,enrollment:decodedToken.enrollment,id:decodedToken.id})
    } catch (error) {
        return res.json({success:false,message:error.message})
    }
})

securityRouter.post('/scanGatePass',authMiddleware,async(req,res)=>{
    try {
        // The security guard selects a session(entry/exit) and then scans the qr code(generated by system=>valid) 
        // where an enrollment appears then the guard hits accept or reject and id of that gatepass is input here.
        const session=req.body.session,signal=req.body.signal,id=req.body.id

        if(session=='exit'){
            if(signal=='reject'){
                await pool.query(
                    "DELETE FROM pass WHERE id = $1",
                    [id]
                );
                return res.json({success:false,message:'Gatepass rejected for exit'})
            }
            else{
                const result=await pool.query(
                    "SELECT * FROM pass WHERE id = $1",
                    [id]
                )
                if(result.rows[0].scanout==true){
                    return res.json({success:false,message:'Gatepass already scanned for exit'})
                }
                else{
                    await pool.query(
                        "UPDATE pass SET exit_time=CURRENT_TIMESTAMP,scanout=TRUE WHERE id=$1",
                        [id]
                    );
                    return res.json({success:true,message:'Gatepass scan successful for exit'})
                }
            }
        }
        else{
            const result=await pool.query(
                "SELECT * FROM pass WHERE id = $1",
                [id]
            )
            const enrollment=result.rows[0].enrollment

            if(signal=='accept'){
                if(result.rows[0].scanin==true){
                    return res.json({success:false,message:'Gatepass already scanned for entry'})
                }
                else{
                    await pool.query(
                        `UPDATE pass
                        SET entry_time = CURRENT_TIMESTAMP,
                        scanin=TRUE,
                        processed=TRUE,
                        WHERE id = $1`,
                        [id]
                    );
                    return res.json({success:true,message:'Gatepass scan successful for entry'})
                }
            }
        }
    } catch (error) {
        return res.json({success:false,message:error.message})
    }
})

securityRouter.post('/imposeFine',authMiddleware,async(req,res)=>{ // Student has someone other's pass
    try {
        const enrollment=req.body.enrollment
        const result=await pool.query(
            "SELECT fine_rate from gatepass_rules WHERE id=$1",
            [1]
        )
        const fine=result.rows[0].fine_rate
        await pool.query(
            `UPDATE student
            SET fine=fine+ $1
            WHERE enrollment=$2`,
            [fine,enrollment]
        )
        return res.json({success:true,message:'Fine imposed successfully'})
    } catch (error) {
        return res.json({success:false,message:error.message})
    }
})

securityRouter.post('/processLate',authMiddleware,async(req,res)=>{ // whose token expired(beyond 23:59)
    try {
        const enrollment=req.body.enrollment

        const curr_time=new Date(
            date.getFullYear(),  
            date.getMonth(),    
            date.getDate(),      
            date.getHours(),
            date.getMinutes(),
            date.getSeconds()
        )
        const result=await pool.query(
            "SELECT fine_rate from gatepass_rules WHERE id=$1",
            [1]
        )
        const fine=result.rows[0].fine_rate
        await pool.query(
            "UPDATE student SET fine=fine+$1 WHERE enrollment=$2",
            [fine,enrollment]
        )
        await pool.query(
            `UPDATE pass 
            SET entry_time=$1,scanin=TRUE,processed=TRUE
            WHERE enrollment=$2 AND processed=FALSE`,
            [curr_time,enrollment]
        )
    } catch (error) {
        return res.json({success:false,message:error.message})
    }
})

export default securityRouter