import express from 'express'
import { authMiddleware } from '../middleware/authMiddleware.js'
import pool from '../config/pool.js'
import jwt from 'jsonwebtoken'

const securityRouter=express.Router()

securityRouter.post('/decodeGatepass',authMiddleware,async(req,res)=>{
    try {
        const gatepassToken=req.body.gatepassToken
        const secret=process.env.JWT_SECRET
        const decodedToken=await jwt.verify(gatepassToken,secret)
        return res.json({success:true,enrollment:decodedToken.enrollment,id:decodedToken.id})
    } catch (error) {
        return res.json({success:false,message:error.message})
    }
})

securityRouter.post('/scanGatePass',authMiddleware,async(req,res)=>{
    try {
        // The security guard selects a session(entry/exit) and then scans the qr code(generated by system=>valid) 
        // where an enrollment appears then the guard hits accept or reject and id of that gatepass is input here.
        const session=req.body.session,signal=req.body.signal,id=req.body.id

        if(session=='exit'){
            if(signal=='reject'){
                await pool.query(
                    "DELETE FROM pass WHERE id = $1",
                    [id]
                );
                return res.json({success:false,message:'Gatepass Denied'})
            }
            else{
                const result=await pool.query(
                    "SELECT * FROM pass WHERE id = $1",
                    [id]
                )
                if(result.rows[0].scanout==true){
                    return res.json({success:false,message:'Gatepass already scannedout'})
                }
                else{
                    await pool.query(
                        "UPDATE pass SET exit_time=CURRENT_TIMESTAMP,scanout=$2 WHERE id=$1",
                        [id,true]
                    );
                    return res.json({success:true,message:'Gatepass Granted'})
                }
            }
        }
        else{
            if(signal=='accept'){
                const result=await pool.query(
                    "SELECT * FROM pass WHERE id = $1",
                    [id]
                )
                if(result.rows[0].scanin==true){
                    return res.json({success:false,message:'Gatepass already scannedin'})
                }
                else{
                    await pool.query(
                        `UPDATE pass
                        SET entry_time = CURRENT_TIMESTAMP,
                        scanin=$2
                        WHERE id = $1`,
                        [id,true]
                    );
                    return res.json({success:true,message:'Gatepass Accepted'})
                }
            }
            else{
                await pool.query(
                    "DELETE FROM pass WHERE id = $1",
                    [id]
                );
                return res.json({success:true,message:'Gatepass Rejected'})
            }
        }
    } catch (error) {
        return res.json({success:false,message:error.message})
    }
})

export default securityRouter