import express from 'express'
import { authMiddleware } from '../middleware/authMiddleware.js'
import pool from '../config/pool.js'

const securityRouter=express.Router()

securityRouter.post('/scanGatePass',authMiddleware,async(req,res)=>{
    try {
        // The security guard selects a session(entry/exit) and then scans the qr code(generated by system=>valid) 
        // where an enrollment appears then the guard hits accept or reject and id of that gatepass is input here.
        const session=req.body.session,signal=req.body.signal,id=req.body.id
        if(session=='exit'){
            if(signal=='reject'){
                await pool.query(
                    "DELETE FROM pass WHERE id = $1",
                    [id]
                );
                return res.json({success:false,message:'Gatepass Denied'})
            }
            else{
                await pool.query(
                    "UPDATE pass SET exit_time=CURRENT_TIMESTAMP WHERE id=$1",
                    [id]
                );
                return res.json({success:true,message:'Gatepass Granted'})
            }
        }
        else{
            if(signal=='accept'){
                await pool.query(
                    `UPDATE pass
                    SET entry_time = CURRENT_TIMESTAMP
                    WHERE id = $1`,
                    [id]
                );

                return res.json({success:false,message:'Gatepass Accepted'})
            }
            else{
                await pool.query(
                    "DELETE FROM pass WHERE id = $1",
                    [id]
                );
                return res.json({success:true,message:'Gatepass Rejected'})
            }
        }
    } catch (error) {
        return res.json({success:false,message:error.message})
    }
})

export default securityRouter